# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł')),
                ('min_players_number', models.IntegerField(verbose_name='Minimalna liczba graczy')),
                ('max_players_number', models.IntegerField(verbose_name='Maksymalna liczba graczy')),
                ('max_game_time', models.IntegerField(verbose_name='Czas gry')),
                ('single_player_mode', models.BooleanField(default=False, verbose_name='Dla jednego gracza')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='board.Genre', verbose_name='Gatunek'),
        ),
    ]
